# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=models.CharField(max_length=20, unique=True, verbose_name='手机号'), max_length=64, verbose_name='昵称'),
        ),
    ]
