# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190401_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=None, max_length=64, verbose_name='昵称'),
        ),
    ]
