# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-02 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import tools.model_to_dict


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190401_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='北京', max_length=16, verbose_name='目标城市')),
                ('min_distance', models.PositiveIntegerField(default=0, verbose_name='最小查找范围')),
                ('max_distance', models.PositiveIntegerField(default=50, verbose_name='最大查找范围')),
                ('min_dating_age', models.PositiveIntegerField(default=18, verbose_name='最小交友年龄')),
                ('max_dating_age', models.PositiveIntegerField(default=50, verbose_name='最大交友年龄')),
                ('dating_sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=8, verbose_name='匹配的性别')),
                ('vibration', models.BooleanField(default=True, verbose_name='开启震动')),
                ('only_matche', models.BooleanField(default=True, verbose_name='不让为匹配的人看我的相册')),
                ('auto_play', models.BooleanField(default=True, verbose_name='自动播放视频')),
            ],
            options={
                'db_table': 'profiles',
            },
            bases=(models.Model, tools.model_to_dict.ModelMixin),
        ),
    ]
