# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-02 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='隔壁老王', max_length=64, verbose_name='昵称'),
        ),
    ]
